name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Make Gradle Wrapper Executable
        run: chmod +x gradlew

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          gradle-home-cache-cleanup: true

      - name: Publish to Modrinth
        uses: gradle/gradle-build-action@v2
        if: ${{ success() && github.repository == 'onebeastchris/customplayerheads' && github.ref_name == 'master' }}
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        with:
          arguments: modrinth
          gradle-home-cache-cleanup: true
